<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Workshop Week 10</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Week10_files/libs/clipboard/clipboard.min.js"></script>
<script src="Week10_files/libs/quarto-html/quarto.js"></script>
<script src="Week10_files/libs/quarto-html/popper.min.js"></script>
<script src="Week10_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Week10_files/libs/quarto-html/anchor.min.js"></script>
<link href="Week10_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Week10_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Week10_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Week10_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Week10_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#section-1-back-to-linear-logistic-models" id="toc-section-1-back-to-linear-logistic-models" class="nav-link active" data-scroll-target="#section-1-back-to-linear-logistic-models">SECTION 1: back to linear &amp; logistic models</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#posterior-predictive-check" id="toc-posterior-predictive-check" class="nav-link" data-scroll-target="#posterior-predictive-check">Posterior Predictive Check</a></li>
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">Linearity</a></li>
  <li><a href="#homogeneity-of-variance" id="toc-homogeneity-of-variance" class="nav-link" data-scroll-target="#homogeneity-of-variance">Homogeneity of Variance</a></li>
  <li><a href="#influential-observations" id="toc-influential-observations" class="nav-link" data-scroll-target="#influential-observations">Influential Observations</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals">Normality of Residuals</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#section-2-logistic-regression" id="toc-section-2-logistic-regression" class="nav-link" data-scroll-target="#section-2-logistic-regression">SECTION 2: logistic regression</a>
  <ul class="collapse">
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">QUESTION 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">QUESTION 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">QUESTION 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">QUESTION 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">QUESTION 7</a></li>
  </ul></li>
  <li><a href="#section-3-bootstrapping" id="toc-section-3-bootstrapping" class="nav-link" data-scroll-target="#section-3-bootstrapping">SECTION 3: bootstrapping</a>
  <ul class="collapse">
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">QUESTION 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">QUESTION 9</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">QUESTION 10</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Workshop Week 10</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="section-1-back-to-linear-logistic-models" class="level1">
<h1>SECTION 1: back to linear &amp; logistic models</h1>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>Briefly describe what this function <code>check_model()</code> does and why it might be more efficient than running individual tests manually.</p>
<p>This function runs a <strong>comprehensive set of model assumption checks all at once</strong>, producing a visual diagnostic output in a single call.</p>
<p>From the documentation, it consolidates several individual checks that the package offers separately, including <code>check_collinearity()</code>, <code>check_normality()</code>, and <code>check_heteroscedasticity()</code>, among others. Rather than calling each of these one by one, <code>check_model()</code> bundles them into one unified visualization.</p>
<p>The practical advantage is straightforward; instead of writing and running multiple lines of diagnostic code, interpreting each result in isolation, and mentally piecing together an overall picture of model health, you get everything surfaced at once. This is especially useful during exploratory modeling, where you want a quick sanity check on assumptions before committing to a model. It reduces the cognitive overhead of juggling multiple outputs and makes it easier to spot if <em>several</em> assumptions are violated simultaneously, which might point to a more fundamental modeling issue rather than an isolated one.</p>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>We want to investigate the relationship between body mass index (<code>bmi</code>) and blood glucose levels (<code>blood_glucose_level</code>).</p>
<ol type="1">
<li><p>Run a linear model predicting blood glucose levels based on BMI.</p></li>
<li><p>Use the <code>check_model()</code> function to generate a diagnostic report.</p></li>
<li><p>Analyze the resulting graphs. Based on the visual evidence, is this model “safe” to use? Explain what each plot (Posterior Predictive Check, Linearity, Homoskedasticity, etc.) tells you about this specific relationship.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>diabetes <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"diabetes_subsample.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear model: blood glucose ~ BMI</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>model_bmi <span class="ot">&lt;-</span> <span class="fu">lm</span>(blood_glucose_level <span class="sc">~</span> bmi, <span class="at">data =</span> diabetes)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_bmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = blood_glucose_level ~ bmi, data = diabetes)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.798 -38.601   2.748  20.399 161.399 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 130.5910     5.4627  23.906   &lt;2e-16 ***
bmi           0.2932     0.1945   1.507    0.132    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 41.18 on 998 degrees of freedom
Multiple R-squared:  0.002271,  Adjusted R-squared:  0.001271 
F-statistic: 2.272 on 1 and 998 DF,  p-value: 0.1321</code></pre>
</div>
</div>
<p>The model finds no significant linear relationship between BMI and blood glucose level (β = 0.29, p = .132), and the near-zero R² (0.002) indicates that BMI explains less than 1% of the variance in blood glucose.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#| label: check-model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.width: 16</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig.height: 12</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| dev: "png"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#| dpi: 150</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>plots <span class="ot">&lt;-</span> <span class="fu">check_model</span>(model_bmi, <span class="at">panel =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PP_CHECK</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$NCV</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$HOMOGENEITY</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$OUTLIERS</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$QQ</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="posterior-predictive-check" class="level3">
<h3 class="anchored" data-anchor-id="posterior-predictive-check">Posterior Predictive Check</h3>
<p>The posterior predictive check reveals an immediate and fundamental concern with this model. The observed data (dark green line) displays a clearly bimodal distribution, with one peak around a blood glucose level of approximately 80 and a second, taller peak around 150-160. The model-predicted lines fail to replicate this pattern entirely, instead generating a single smooth unimodal hump centered around the higher peak. This tells us that the model is assuming the outcome comes from one homogeneous population, when the data clearly suggests there are two distinct subgroups present. This is arguably the most serious finding in this diagnostic report, as it indicates a fundamental mismatch between what the model assumes about the data and what the data actually looks like.</p>
</section>
<section id="linearity" class="level3">
<h3 class="anchored" data-anchor-id="linearity">Linearity</h3>
<p>The linearity plot shows residuals on the y-axis plotted against fitted values on the x-axis, with a green reference line that should ideally sit flat at zero across the entire range. Here, the fitted values span a narrow range from approximately 133 to 150. The reference line starts relatively flat between fitted values of 133 and 140, but then curves noticeably upward after 145, swinging toward the upper right of the plot. This upward curl indicates that as predicted values increase, the model systematically underestimates the outcome. A truly linear relationship would produce a reference line that stays horizontal throughout, so this deviation tells us the underlying relationship has some curvature that a straight line cannot adequately capture.</p>
</section>
<section id="homogeneity-of-variance" class="level3">
<h3 class="anchored" data-anchor-id="homogeneity-of-variance">Homogeneity of Variance</h3>
<p>The homogeneity of variance plot, also known as the scale-location plot, displays the square root of standardized residuals against fitted values. If the assumption of constant variance (homoskedasticity) held, the green reference line would be flat and the dots would form an even horizontal band. Instead, the reference line begins around 0.85-0.90 on the left side and climbs steadily to approximately 1.1-1.15 by the right side of the plot. While this is not a dramatic spike, the consistent upward trend across the entire range of fitted values is meaningful. It indicates that the model’s errors grow larger as predicted values increase, a violation known as heteroskedasticity. The practical consequence of this is that the standard errors produced by the model are not equally reliable across all predicted values, which in turn means that p-values and confidence intervals, particularly at the higher end, should be treated with caution.</p>
</section>
<section id="influential-observations" class="level3">
<h3 class="anchored" data-anchor-id="influential-observations">Influential Observations</h3>
<p>The vast majority of data points are clustered tightly near zero leverage with standardized residuals comfortably between -2 and +2. A handful of labelled observations (821, 397, 350, 225) show slightly elevated leverage around 0.003-0.005, but their standardized residuals remain close to zero, meaning they are not badly mispredicted. The point with the highest leverage, observation 802 at approximately 0.032, similarly has a residual near zero. Crucially, all observations fall well within the Cook’s distance contour lines, which represent the threshold beyond which a point would be considered disproportionately influential. This assumption is satisfactorily met: no single data point is tilting the regression line in a meaningful way.</p>
</section>
<section id="normality-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="normality-of-residuals">Normality of Residuals</h3>
<p>This plot displays deviations from expected normal quantiles rather than the raw quantiles themselves, which is why it looks different from a classic QQ plot. Ideally the dots would track closely along the horizontal green line at zero throughout. What we observe instead is that on the far left (around x = -2.5 to -2), the dots start high at around +1.5 to +2.1 before dropping steeply. Through the middle section the dots follow a wavy, staircase-like pattern rather than a smooth curve, hovering near but not on zero. On the right side there is a sharp upward jump to around +1 to +1.5 before the final point drops back down. The jagged staircase pattern through the middle is characteristic of an outcome variable that is discrete or heavily rounded, meaning the residuals only take on certain values rather than varying continuously. The sharp deviations at both tails indicate the residual distribution is not normal. This finding is consistent with the bimodal structure already observed in the posterior predictive check.</p>
<ul>
<li><p>Based on the visual evidence across these five diagnostic plots, this model is not safe to interpret in its current form. Four out of five assumptions show meaningful violations, and they all point toward the same underlying problem.</p></li>
<li><p>The posterior predictive check is the clearest signal: the model cannot reproduce the shape of the actual data because it is blind to what appears to be two distinct subgroups within the sample. This may mean the model is fundamentally misrepresenting the population it is trying to describe.</p></li>
</ul>
</section>
</section>
</section>
<section id="section-2-logistic-regression" class="level1">
<h1>SECTION 2: logistic regression</h1>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">QUESTION 3</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> bmi <span class="sc">+</span> age <span class="sc">+</span> gender, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> diabetes, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> binomial)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ bmi + age + gender, family = binomial, 
    data = diabetes)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.5208  -0.4746  -0.2823  -0.1490   2.9083  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -7.634194   0.730457 -10.451  &lt; 2e-16 ***
bmi           0.081614   0.016057   5.083 3.72e-07 ***
age           0.052016   0.007324   7.102 1.23e-12 ***
genderMale    0.495948   0.236105   2.101   0.0357 *  
genderOther -11.022431 535.411199  -0.021   0.9836    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 605.08  on 999  degrees of freedom
Residual deviance: 503.75  on 995  degrees of freedom
AIC: 513.75

Number of Fisher Scoring iterations: 12</code></pre>
</div>
</div>
<p>The model showed a significant improvement over the null model, with deviance dropping from 605.08 to 503.75, indicating that the predictors collectively carry meaningful information about diabetes status.</p>
<p>The intercept of -7.63 represents the log-odds of having diabetes when BMI is zero, age is zero, and gender is the reference category (Female). This is not a meaningful real-world value since nobody has a BMI or age of zero, but it serves as the mathematical baseline from which all other effects are calculated.</p>
<p>We will look into effect size by exponentiating the coefficient (hard to interpret log-odds, so we go for odds-ratio)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert log-odds to odds ratios</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model_logistic))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          bmi          age   genderMale  genderOther 
4.836283e-04 1.085036e+00 1.053392e+00 1.642055e+00 1.633124e-05 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With confidence intervals</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(model_logistic), <span class="fu">confint</span>(model_logistic)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      OR        2.5 %       97.5 %
(Intercept) 4.836283e-04 0.0001076579 1.901072e-03
bmi         1.085036e+00 1.0513757254 1.120057e+00
age         1.053392e+00 1.0389097406 1.069235e+00
genderMale  1.642055e+00 1.0341678215 2.615851e+00
genderOther 1.633124e-05           NA 3.965658e+42</code></pre>
</div>
</div>
<p>BMI emerged as a significant predictor of diabetes (β = 0.082, z = 5.08, p &lt; .001). Exponentiating the coefficient yields an odds ratio of 1.085 (95% CI [1.051, 1.120]), meaning that each one unit increase in BMI is associated with an 8.5% increase in the odds of having diabetes, holding age and gender constant. The confidence interval is narrow and falls entirely above 1, confirming the reliability of this effect.</p>
<p>Regarding the control variables, both age (OR = 1.053, p &lt; .001) and gender (OR = 1.642 for males vs.&nbsp;females, p = .036) were also significant predictors, indicating that older individuals and males have higher odds of diabetes.</p>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">QUESTION 4</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>plots_logistic <span class="ot">&lt;-</span> <span class="fu">check_model</span>(model_logistic, <span class="at">panel =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plots_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PP_CHECK</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/check-model-logistic-1.png" class="img-fluid figure-img" width="1000"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$BINNED_RESID</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/check-model-logistic-2.png" class="img-fluid figure-img" width="1000"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$OUTLIERS</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/check-model-logistic-3.png" class="img-fluid figure-img" width="1000"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$VIF</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/check-model-logistic-4.png" class="img-fluid figure-img" width="1000"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$QQ</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/check-model-logistic-5.png" class="img-fluid figure-img" width="1000"></p>
</figure>
</div>
</div>
</div>
<p>The posterior predictive check shows the model-predicted and observed data points sitting virtually on top of each other, confirming that choosing a logistic distribution was the right call for a binary outcome. The uniformity of residuals plot reinforces this: the dots track almost perfectly along the diagonal, which is a clean result. Collinearity is also a non-issue, with age and BMI both showing VIF values near 1, meaning they are providing independent information and the model can cleanly separate their effects. Influential observations are all within Cook’s distance contours, so no single data point is distorting the results.</p>
<p>The one genuine concern is the binned residuals plot. At the lower end of predicted probabilities (roughly 0-15%), several points fall outside the error bounds and are flagged in red, indicating the model is systematically mispredicting for individuals it assigns a low probability of diabetes to. This is a partial violation of the linearity of the logit assumption, suggesting the relationship between the predictors and log-odds may not be perfectly linear across the full range. That said, this violation is confined to one region of the probability range and does not undermine the model wholesale.</p>
<p>The takeaway is that the coefficients and odds ratios reported earlier can be interpreted with reasonable confidence, particularly for individuals in the moderate-to-high risk range. The low probability range deserves some caution.</p>
</section>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">QUESTION 5</h2>
<p><strong>Solution 1: Linear Probability Model</strong></p>
<p>This is literally just running a normal <code>lm()</code> on your diabetes variable even though it’s 0/1. The coefficient now directly means “percentage point change in probability”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model_lpm <span class="ot">&lt;-</span> <span class="fu">lm</span>(diabetes <span class="sc">~</span> bmi <span class="sc">+</span> age <span class="sc">+</span> gender, <span class="at">data =</span> diabetes)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = diabetes ~ bmi + age + gender, data = diabetes)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.33879 -0.13982 -0.07489 -0.00519  0.97634 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.1934527  0.0378743  -5.108 3.91e-07 ***
bmi          0.0054419  0.0013749   3.958 8.09e-05 ***
age          0.0028092  0.0004167   6.741 2.66e-11 ***
genderMale   0.0379739  0.0175728   2.161   0.0309 *  
genderOther -0.1097273  0.2748431  -0.399   0.6898    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2746 on 995 degrees of freedom
Multiple R-squared:  0.0842,    Adjusted R-squared:  0.08052 
F-statistic: 22.87 on 4 and 995 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear probability model confirms that BMI, age, and gender are all significant predictors of diabetes, consistent with the logistic regression findings. However the coefficients are now directly interpretable in probability terms, which is considerably more intuitive.</p>
<p>Each one unit increase in BMI is associated with a 0.54 percentage point increase in the probability of having diabetes (p &lt; .001). Each additional year of age increases the probability by 0.28 percentage points (p &lt; .001). Being male is associated with a 3.8 percentage point higher probability of diabetes compared to females (p = .031). The genderOther category remains non-significant and unreliable (small sample near 0).</p>
<p>Compared to the logistic regression in Question 3, these results are substantially easier to communicate. Rather than saying “each unit increase in BMI multiplies the odds of diabetes by 1.085”, we can simply say “each unit increase in BMI increases the probability of diabetes by about half a percentage point.”</p>
<p>The tradeoff, as the professor notes, is that the model makes no guarantee about staying within the 0-1 probability range: the intercept here is already -0.19, meaning the model technically predicts a negative probability of diabetes for someone with very low BMI and age, which is mathematically impossible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Linear Probability Model"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"BMI"</span>, <span class="at">y =</span> <span class="st">"Probability of Diabetes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The graph confirms what we saw in the regression (the negative intercept).</p>
<p>The plot shows the regression line starting below zero on the left side. at low BMI values (around 15-18) the line dips into negative probability territory, which is mathematically impossible. You cannot have a negative probability of having diabetes. The linear model has no built-in constraint forcing predictions to stay between 0 and 1, so at the extremes it produces nonsensical values.</p>
<p>At the higher end the line reaches about 0.45 at BMI of 65+, which stays below 1 so no problem there, but the negative predictions at the low end are enough to illustrate the core weakness of the LPM. In reality, someone with a very low BMI doesn’t have a negative probability of diabetes, their probability is just very low, approaching zero but never crossing it.</p>
<p><strong>Solution 2 — Average Marginal Effects</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(model_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Term       Contrast Estimate Std. Error     z Pr(&gt;|z|)    S    2.5 %
 age    dY/dX           0.00377   0.000545  6.92   &lt;0.001 37.7  0.00270
 bmi    dY/dX           0.00592   0.001156  5.12   &lt;0.001 21.6  0.00365
 gender Male - Female   0.03670   0.017724  2.07   0.0384  4.7  0.00196
 gender Other - Female -0.07479   0.010374 -7.21   &lt;0.001 40.7 -0.09512
   97.5 %
  0.00484
  0.00818
  0.07144
 -0.05446

Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
<p>For BMI specifically, the AME of 0.00592 means that on average, a one unit increase in BMI is associated with a 0.59 percentage point increase in the probability of having diabetes, holding age and gender constant. This effect is statistically significant (p &lt; .001) with a tight confidence interval ranging from 0.37% to 0.82%, meaning we can be confident the true effect sits in that range and is reliably positive.</p>
<p>For age, each additional year is associated with a 0.38 percentage point increase in diabetes probability on average (p &lt; .001, CI [0.27%, 0.48%]).</p>
<p>For gender, males have on average a 3.67 percentage point higher probability of diabetes than females (p = .038, CI [0.20%, 7.14%]). The wider confidence interval here reflects more uncertainty around this estimate compared to BMI and age.</p>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">QUESTION 6</h2>
<ol type="1">
<li>Let’s look at the relationship between BMI and Diabetes using standard&nbsp;<code>ggplot2</code>&nbsp;tools. We will compare a Linear Model (LM) and a Logistic Model (GLM).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. The Linear Approach (Straight line)</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Linear Probability Model"</span>, <span class="at">subtitle =</span> <span class="st">"A straight line for a binary outcome"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. The Logistic Approach (S-Curve)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Logistic Model"</span>, <span class="at">subtitle =</span> <span class="st">"The S-curve (sigmoïd)"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Linear probability model: The blue line is a straight shot across the plot which makes it easy to read, but the problem is immediately visible: at low BMI values the line dips below zero, predicting a negative probability of diabetes which makes no sense. A probability can’t be negative.</p>
<p>Logistic model: The red curve tells a more realistic story. It starts flat and close to zero at low BMI, steepens through the middle range, and begins flattening again at high BMI without ever crossing below 0 or above 1. This is the S-curve in action.</p>
<p>Both models agree that higher BMI means higher diabetes risk, but the logistic curve is clearly the more honest representation. The linear line’s simplicity comes at the cost of producing impossible predictions at the extremes, while the logistic curve stays realistic across the whole BMI range. This is exactly why logistic regression exists for binary outcomes.</p>
<ol start="2" type="1">
<li>Solving the bivariate problem using marginaleffects package</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing the effect of BMI while "controlling" for Age and Gender</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Linear model:</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>model_lin <span class="ot">&lt;-</span> <span class="fu">lm</span>(diabetes <span class="sc">~</span> bmi <span class="sc">+</span> age <span class="sc">+</span> gender, <span class="at">data =</span> diabetes)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_predictions</span>(model_lin, <span class="at">condition =</span> <span class="st">"bmi"</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Adjusted Predictions of Diabetes"</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Holding Age and Gender at their mean/mode"</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Probability of Diabetes"</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BMI"</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Logistic:</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>model_log <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> bmi <span class="sc">+</span> age <span class="sc">+</span> gender, <span class="at">family =</span> binomial, <span class="at">data =</span> diabetes)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_predictions</span>(model_log, <span class="at">condition =</span> <span class="st">"bmi"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Adjusted Predictions of Diabetes"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Holding Age and Gender at their mean/mode"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Probability of Diabetes"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BMI"</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Linear model (first plot)</strong></p>
<p>The line starts just above zero around BMI 15 and rises steadily to about 0.27 at BMI 65. It’s a straight constant slope all the way through. Compared to the raw bivariate plot from before, the line is noticeably lower and flatter, that’s the controlling at work. Once you account for the fact that age and gender also contribute to diabetes risk, BMI’s isolated effect is more modest than it appeared on its own.</p>
<p><strong>Logistic model (second plot)</strong></p>
<p>The curve starts near zero at low BMI, stays flat through BMI 20-30, then accelerates upward, reaching around 0.45 by BMI 65. The confidence interval also widens considerably at higher BMI values, reflecting that there are fewer people with very high BMI in the sample so the model is less certain there. Again, compared to the raw logistic plot, the adjusted predictions are lower — same reason, age and gender are being held constant so BMI isn’t carrying their weight anymore.</p>
<p>Both plots tell the same story as before — higher BMI means higher diabetes risk — but the adjusted predictions are more honest because they show BMI’s effect in isolation rather than tangled up with age and gender.</p>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">QUESTION 7</h2>
<p>Think about everything you’ve just done. You’ve learned about multiple ways to talk about the results of a regression with a binary outcome. Imagine that you’re working as a data scientists for a health agency and you’re trying to understand the effect of bmi on diabetes. What would be the most efficient way to communicate your results to people?</p>
<p>For a health agency audience you have to assume the people reading your report are not statisticians — they’re policymakers, doctors, or public health officials who need to make decisions based on your findings, or literally just people trying to make sense of results.</p>
<p>The most efficient approach would be to lead with the AME and the adjusted prediction plot together. The AME gives you one clean sentence: a one unit increase in BMI is associated with a 0.59 percentage point increase in the probability of having diabetes, holding age and gender constant. That’s immediately understandable to anyone. Then the adjusted prediction plot from <code>plot_predictions()</code> gives the visual story, you can literally see the curve accelerating after BMI 40 and point to it in a presentation without any statistical training required.</p>
</section>
</section>
<section id="section-3-bootstrapping" class="level1">
<h1>SECTION 3: bootstrapping</h1>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">QUESTION 8</h2>
<p>Explain in what circumstances using bootstrapped confidence intervals can be better than what we’ve done so far.</p>
<p>The most obvious case is the linear model predicting blood glucose from BMI. The diagnostic plots clearly showed the residuals were non-normal and the outcome was bimodal — two distinct subgroups present in the data. Every confidence interval and p-value that model produced was computed assuming normally distributed errors, which the diagnostics proved wasn’t the case. Bootstrap doesn’t make that assumption, it works with the actual shape of your data, so the uncertainty estimates it produces would have been more honest.</p>
<p>On the logistic model specifically, bootstrap can help in a meaningful way. The binned residuals plot showed systematic misprediction at low predicted probabilities, which hints that the model is struggling in that region. The standard confidence intervals around our coefficients and odds ratios assume the model is correctly specified and that the sampling distribution of the estimates is approximately normal. Bootstrap doesn’t assume either of those things, it would ask “if we resampled this dataset repeatedly, how much would our estimates move around?” That gives you a more honest picture of uncertainty, particularly in the low probability region where the model was already showing signs of strain.</p>
<p>(Potentially) The confidence intervals we reported for the average marginal effect of BMI were still computed under standard distributional assumptions. A bootstrap confidence interval around that same estimate would allow for a more meaningful statement to a health agency audience, instead of reporting a p-value, we could say “there is only a 2.5% chance the true effect is zero or negative”, which is the kind of plain probability statement that actually informs real decisions rather than hiding behind statistical jargon that most people misinterpret anyway.</p>
</section>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">QUESTION 9</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(diabetes<span class="sc">$</span>blood_glucose_level)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution is clearly not normal and has a multimodal structure. There’s a large cluster of people with blood glucose around 80-100, then the frequency drops, peaks again heavily around 140-160, drops sharply, and then there’s a smaller separate cluster around 200.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># STEP 1: Create an empty "bucket" (vector) to hold our results</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We will do this 500 times</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>n_iterations <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>glucose_estimates <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_iterations)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># STEP 2: The Loop (The "Manual" work)</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iterations) {</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># A. Create a "Resample" (Pick rows at random with replacement)</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  boot_data <span class="ot">&lt;-</span> diabetes[<span class="fu">sample</span>(<span class="fu">nrow</span>(diabetes), <span class="at">replace =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># B. Run the model on THIS specific simulated dataset</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  boot_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> blood_glucose_level <span class="sc">+</span> age, </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> boot_data)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># C. Save the Glucose coefficient into our "bucket" at position i</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  glucose_estimates[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(boot_model)[<span class="st">"blood_glucose_level"</span>]</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># For pedagogu: Print progress every 100 times so students see it working</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(i <span class="sc">%%</span> <span class="dv">100</span> <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Simulation number"</span>, i, <span class="st">"complete!"</span>))</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Simulation number 100 complete!"
[1] "Simulation number 200 complete!"
[1] "Simulation number 300 complete!"
[1] "Simulation number 400 complete!"
[1] "Simulation number 500 complete!"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># STEP 3: Turn the bucket into a table for plotting</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>results_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">estimate =</span> glucose_estimates)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># STEP 4: Visualize the results</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. First, get the "Original Result" from your main model</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>model_glucose <span class="ot">=</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> blood_glucose_level <span class="sc">+</span> age, </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> diabetes)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>original_slope <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_glucose)[<span class="st">"blood_glucose_level"</span>]</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Plot the histogram</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> estimate)) <span class="sc">+</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The bars: represent the 500 "simulated" worlds</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"firebrick"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># The line: represents the "original" result from our real data</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> original_slope, </span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"blue"</span>, </span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="fl">1.5</span>, </span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a label to know what the blue line is</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> original_slope, <span class="at">y =</span> <span class="dv">10</span>, <span class="at">label =</span> <span class="st">"Original Estimate"</span>, </span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"The Bootstrap Distribution"</span>,</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"The blue dashed line is our original model result"</span>,</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Effect size of Blood Glucose (Slope)"</span>,</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"How many times it happened in 500 tries"</span>) <span class="sc">+</span></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In your own words, describe what the code does step by step. Then explain the resulting graph. What do you conclude as to the effect of blood glucose on diabetes?</p>
<p>First step is we set up a bucket, which is essentially an empty container of 500 zeros. Each row will eventually hold one estimate of the blood glucose coefficient. Second step is the loop which is the heart of the bootstrap it runs 500 times and each time it does three things : (1) resample the data (with replacement tho, same person can be picked multiple times) to create different versions of my dataset each time (2) run my logistic regression on the resampled dataset (3) at last we take just the blood glucose coefficient from the model and store in in a slot of the bucket created earlier. after 500 loops we get 500 slightly different estimates. Step 3 we turn that bucket into a table/ data frame of some sort and then step 4 we visualise the historgram that shows the distribution of the 500 estimates: our bootstrap distribution. Then we add the blue line which is the estimate from my actual real data sitting inside that distribution.</p>
<p>The bootstrap distribution shows the effect of blood glucose on diabetes probability across 500 simulated resamples of the dataset. The entire distribution sits between approximately 0.026 and 0.045, with every single one of the 500 iterations producing a positive coefficient. Not one resample returned a zero or negative effect, which is about as strong a signal as bootstrap can give us.</p>
<p>The original estimate from the real data (blue dashed line, sitting around 0.033) falls naturally within the bulk of the distribution rather than at an extreme, confirming it is a stable and representative result rather than a fluke of one particular sample.</p>
<p>The distribution is reasonably tight, meaning there is limited uncertainty about the direction and approximate magnitude of the effect. The 95% bootstrap confidence interval would run from roughly the left tail to the right tail of this histogram, somewhere between 0.028 and 0.040, and crucially the entire interval is above zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#want to find the confidence interval</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(glucose_estimates, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5%      97.5% 
0.02890716 0.03925509 </code></pre>
</div>
</div>
<p>The conclusion is clear: blood glucose has a consistent, reliable positive effect on the probability of having diabetes. This finding does not depend on any assumptions about normality or distributional shape, it comes directly from the data itself repeated 500 times.</p>
</section>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">QUESTION 10</h2>
<p>Using this dataset, determine a research question of your choice and test your hypothesis using bootstrapping.</p>
<p><strong>Research Question:</strong> Does smoking history affect the probability of having heart disease, controlling for age and gender?</p>
<p>We hypothesize that current and former smokers have a significantly higher probability of having heart disease compared to individuals who have never smoked, even after controlling for age and gender. Individuals who have never smoked are expected to show the lowest rates of heart disease, while current smokers are expected to show the highest, with former smokers falling somewhere in between reflecting the partial recovery effect of quitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram to see what my categorical variable looks like</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes, <span class="fu">aes</span>(<span class="at">x =</span> smoking_history)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Smoking History"</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Smoking History"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Recode smoking history into 3 clean groups, drop No Info</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>diabetes_clean <span class="ot">&lt;-</span> diabetes <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(smoking_history <span class="sc">!=</span> <span class="st">"No Info"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoking_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    smoking_history <span class="sc">==</span> <span class="st">"current"</span> <span class="sc">~</span> <span class="st">"smoker"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    smoking_history <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"ever"</span>, <span class="st">"former"</span>, <span class="st">"not current"</span>) <span class="sc">~</span> <span class="st">"ex_smoker"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    smoking_history <span class="sc">==</span> <span class="st">"never"</span> <span class="sc">~</span> <span class="st">"never"</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoking_group =</span> <span class="fu">factor</span>(smoking_group, </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"never"</span>, <span class="st">"ex_smoker"</span>, <span class="st">"smoker"</span>)))</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Quick check of the new distribution</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes_clean, <span class="fu">aes</span>(<span class="at">x =</span> smoking_group)) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Recoded Smoking Groups"</span>,</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Smoking Group"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(diabetes_clean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 647</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(diabetes_clean<span class="sc">$</span>smoking_group))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    never ex_smoker    smoker 
      355       189       103 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Logistic regression</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>model_smoking <span class="ot">&lt;-</span> <span class="fu">glm</span>(heart_disease <span class="sc">~</span> smoking_group <span class="sc">+</span> age <span class="sc">+</span> gender,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> binomial,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> diabetes_clean)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_smoking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = heart_disease ~ smoking_group + age + gender, family = binomial, 
    data = diabetes_clean)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.0559  -0.2990  -0.1412  -0.0673   3.1753  

Coefficients:
                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            -9.17778    1.20718  -7.603 2.90e-14 ***
smoking_groupex_smoker  0.31285    0.47307   0.661   0.5084    
smoking_groupsmoker     0.59579    0.61612   0.967   0.3335    
age                     0.09335    0.01716   5.440 5.32e-08 ***
genderMale              0.82154    0.42611   1.928   0.0539 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 236.77  on 646  degrees of freedom
Residual deviance: 179.61  on 642  degrees of freedom
AIC: 189.61

Number of Fisher Scoring iterations: 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Odds ratios with confidence intervals</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(model_smoking), <span class="fu">confint</span>(model_smoking)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 OR        2.5 %       97.5 %
(Intercept)            0.0001033101 7.566279e-06 0.0008813621
smoking_groupex_smoker 1.3673098430 5.443824e-01 3.5506657948
smoking_groupsmoker    1.8144581182 5.046676e-01 5.9213410846
age                    1.0978432089 1.063959e+00 1.1384061814
genderMale             2.2740036887 9.990541e-01 5.3900406953</code></pre>
</div>
</div>
<p>Neither smoking group is significant — ex-smoker OR = 1.37 (p = 0.508) and current smoker OR = 1.81 (p = 0.334), and crucially both confidence intervals cross 1 (ex-smoker CI [0.54, 3.55], current smoker CI [0.50, 5.92]), meaning we cannot rule out that the true effect is zero.</p>
<p>Age is the only robust predictor — each additional year increases the odds of heart disease by about 9.8% (OR = 1.098, CI [1.064, 1.138], p &lt; .001). Gender is borderline with males showing about 2.27 times higher odds than females but just missing significance at p = 0.054.</p>
<p>The data does not support the hypothesis.</p>
<p>We now test with bootstrapping.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>n_iterations <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>smoker_estimates <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_iterations)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>ex_smoker_estimates <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_iterations)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>n_iterations <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>smoker_estimates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n_iterations)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>ex_smoker_estimates <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n_iterations)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iterations) {</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  boot_data <span class="ot">&lt;-</span> diabetes_clean[<span class="fu">sample</span>(<span class="fu">nrow</span>(diabetes_clean), <span class="at">replace =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Only run model if all three smoking groups are present in resample</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">all</span>(<span class="fu">c</span>(<span class="st">"never"</span>, <span class="st">"ex_smoker"</span>, <span class="st">"smoker"</span>) <span class="sc">%in%</span> boot_data<span class="sc">$</span>smoking_group)) {</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tryCatch</span>({</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>      boot_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(heart_disease <span class="sc">~</span> smoking_group <span class="sc">+</span> age <span class="sc">+</span> gender,</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>                        <span class="at">family =</span> binomial,</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> boot_data)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>      smoker_estimates[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(boot_model)[<span class="st">"smoking_groupsmoker"</span>]</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>      ex_smoker_estimates[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(boot_model)[<span class="st">"smoking_groupex_smoker"</span>]</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>    }, <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NULL</span>)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(i <span class="sc">%%</span> <span class="dv">100</span> <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Simulation"</span>, i, <span class="st">"complete!"</span>))</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Simulation 100 complete!"
[1] "Simulation 200 complete!"
[1] "Simulation 300 complete!"
[1] "Simulation 400 complete!"
[1] "Simulation 500 complete!"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>smoker_estimates <span class="ot">&lt;-</span> smoker_estimates[<span class="sc">!</span><span class="fu">is.na</span>(smoker_estimates)]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ex_smoker_estimates <span class="ot">&lt;-</span> ex_smoker_estimates[<span class="sc">!</span><span class="fu">is.na</span>(ex_smoker_estimates)]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 7: Confidence intervals</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(smoker_estimates, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     2.5%     97.5% 
-1.267936  2.048773 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(ex_smoker_estimates, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5%      97.5% 
-0.5528397  1.3855021 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 8: Plot both distributions</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>results_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimate =</span> <span class="fu">c</span>(smoker_estimates, ex_smoker_estimates),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Current Smoker"</span>, <span class="st">"Ex Smoker"</span>), <span class="at">each =</span> n_iterations)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bootstrap Distribution"</span>,</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Effect of smoking history on heart disease probability"</span>,</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Coefficient Estimate"</span>,</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Group"</span>) <span class="sc">+</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Week10_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bootstrap distribution shows the estimated effect of smoking history on heart disease probability across 500 resamples of the data. Both the current smoker (pink) and ex-smoker (teal) distributions are centered around zero and straddle it in both directions, meaning the effect is inconsistent across resamples with no clear positive or negative signal. This fails to support the hypothesis that smokers have a higher probability of heart disease than non-smokers.</p>
<p>The current smoker distribution additionally shows extreme outliers at both ends of the x-axis, reflecting instability caused by the small number of current smokers in the sample (n=105). In some resamples, near-zero heart disease cases in that group caused the model to produce unreliable estimates. This instability is itself a finding: it suggests the sample size is insufficient to draw reliable conclusions about current smokers specifically, and that a larger dataset would be needed to properly test this hypothesis.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>